#!/usr/bin/env zsh
# i3wm configuration
tPadID=`xinput| grep 'TouchPad'| awk '{print $6}' | cut -b 4-5`

#echo `xinput| grep 'TouchPad'| awk '{print $6}' | cut -b 4-5`

tapping_id=`xinput list-props $tPadID | grep 'libinput Tapping Enabled (' | awk '{print $4}' | cut -b 2-4`
`xinput set-prop $tPadID $tapping_id 1`
#echo `xinput| grep 'TouchPad'| awk '{print $6}' | cut -b 4-5`

scrolling_id=`xinput list-props $tPadID | grep 'Natural Scrolling Enabled (' | awk '{print $5}' | cut -b 2-4`
`xinput set-prop $tPadID $scrolling_id 0`
#echo `xinput| grep 'TouchPad'| awk '{print $6}' | cut -b 4-5`

nmcli -g name,type connection  show  --active | awk -F: '/ethernet|wireless/ { print $1 }' | while read connection
do
          nmcli con mod "$connection" ipv6.ignore-auto-dns yes
            nmcli con mod "$connection" ipv4.ignore-auto-dns yes
              nmcli con mod "$connection" ipv4.dns "8.8.8.8 8.8.4.4"
                nmcli con down "$connection" && nmcli con up "$connection"
        done

#sudo systemctl stop NetworkManager;
#sudo macchanger -m fa:6b:60:b8:47:10 wlo1;
#sudo systemctl start NetworkManager;

v4l2-ctl --set-fmt-video=width=1378
#Forkgram & 
#artha &
redshift & 
syncthing --no-browser & 
blueman-applet-*

