#!/usr/bin/env python3
import os
import sys
import json

def sysrun(comm):
    stream = os.popen(comm)
    return stream.read()
def read(file):
    with open(file,'r') as f:
        return int(f.read())

module = 'wlo1' # all means all the modules

root = '/home/sirius/.config/polybar/'
file = 'vars.json'
if os.path.exists(root + file) :
    with open(root+file,'r') as f:
        vars = json.load(f)
else:
    vars = {}

if 'nUP' in vars.keys():
    val1p = vars['nUP']
    val2p = vars['nDN']
else:
    val1p = 0
    val2p = 0
val1 =  int(sysrun(f'cat /sys/class/net/{module}/statistics/rx_bytes'))
val2 =  int(sysrun(f'cat /sys/class/net/{module}/statistics/tx_bytes'))
vars['nUP'] = val1
vars['nDN'] = val2
with open(root+file,'w') as f:
        json.dump(vars, f)
dn = val1 - val1p
up = val2 - val2p

def pFormat(v):
    if v/1e6 > 0.1:
        v = v/1e6  ; v = f'{v:-4.2f}MB'
    elif v/1e3 > 0.1:
        v = v/1e3 ;  v = f'{v:-4.2f}KB'
    else :
        v = f'{v:-5.2f}B'
    return v 
print(f'  {pFormat(up)}  {pFormat(dn)} ')
