#!/usr/bin/env zsh
notify-send -t 3000 Asthetic "Setting random wallpaper..." -u normal
#wget "https://source.unsplash.com/1600x900?sunlight" -O ~/Pictures/Wallpapers-Downloaded/img.jpg
#wget "https://source.unsplash.com/1366x768?morning" -O ~/Pictures/Wallpapers-Downloaded/img.jpg
#opt="night"
opt="japan"


wget "https://source.unsplash.com/1366x768?$opt" -O ~/Pictures/Wallpapers-Downloaded/img.jpg

wal -i ~/Pictures/Wallpapers-Downloaded/img.jpg
