#!/usr/bin/env python3
import json, os, sys


root = '/home/sirius/.config/polybar/'
file = 'vars.json'
if os.path.exists(root + file) :
    with open(root+file,'r') as f:
        vars = json.load(f)
else:
    vars = {}

if 'scr' in vars.keys():
    val = vars['scr']
else:
    val = '/home/sirius/Pictures/Screenshots/'

v1 = '/home/sirius/Pictures/Screenshots/'
v2 = '/home/sirius/Pictures/Screenshots/russian/'
nex = {v1:v2, v2:v1}
out = {v1:'P', v2:'ru'}


if len(sys.argv) > 1 and sys.argv[1] == 'switch':
    val = nex[val]
    os.system(f'notify-send -t 1500 Utility "Screenshot path changed " -u normal')
o = out[val]
print(o)

vars['scr'] = val
with open(root + file,'w') as f:
    json.dump(vars,f)






