#!/usr/bin/env python3
import sys
import os

def read(file):
    with open(file,'r') as f:
        return int(f.read())
def write(file, val):
    os.system(f'echo {val}| tee {file} > /dev/null')
# update this file path for your system
file="/sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1/intel_backlight/brightness"
file1="/sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1/intel_backlight/max_brightness"
mx = read(file1)
val = read(file)
delta = 40
out = val*100/mx
if len(sys.argv) == 3:
    delta = int(sys.argv[2])
    if sys.argv[1] == '-inc':
        write(file, val + delta); out = (val+delta)*100/mx
    elif sys.argv[1] == '-dec':
        write(file, val - delta); out = (val-delta)*100/mx
print('%1.0f'%(out))

