#!/usr/bin/env python3
import json
import os
import sys


if __name__ == '__main__':
    root = '/home/sirius/.config/polybar/'
    file = 'vars.json'
    if os.path.exists(root + file) :
        with open(root+file,'r') as f:
            vars = json.load(f)
    else:
        vars = {}


    if 'layout' in vars.keys():
        val = vars['layout']
    else :
        val = 'us'

    nextL = {'ru':'us','us':'es','es':'ru'}
    imgL = {'ru' : 'ru_big.svg', 'es': 'es_big.png' , 'us' : 'us_big.jpg'}
    

    if len(sys.argv) > 1: 
        if sys.argv[1] == 'change':
            val = nextL[val]
            os.system(f'setxkbmap {val}')
        elif sys.argv[1] == 'show':
            os.system(f'setxkbmap us')
            os.system(f'gthumb {root+imgL[val]} & disown   ')
            val = 'us'
            

    
    print(val)

    vars['layout'] = val
    with open(root + file , 'w') as f:
        json.dump(vars, f)


