#!/usr/bin/env python3

import sys, os



if __name__ == '__main__':
    root = '/home/sirius/Pictures/Screenshots/'
    l = os.listdir(root)
    l = [i for i in l if i.startswith('shot_')]
 #   l = list(map(lambda x: x if 'shot_' in x else '0', l))
 #   l = [ i for i in l if i != '0']
    l.sort(key=lambda x:int(x[5:x.find('.')]))
    print(l)
    if not (l[0] == l[-1] and l[0] == '0') :
        s = l[-1]
        a = s.find('_')
        b = s.find('.')
        n = int(s[a+1:b])+1
    else : 
        n = 1
    
    if len(sys.argv) > 1:
        if sys.argv[1] == 'window':
            print(n)
            os.system(f'import -window root {root}shot_{n}.png')
        elif sys.argv[1] == 'custom' :
            os.system(f'import {root}shot_{n}.png')	
os.system('notify-send -t 1500 Utility "Screenshot Captured" -u normal')

